baseURL = "https://bettercap.org/"
languageCode = "en-us"
title = "bettercap"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[params]
themeVariant = "green"
disableShortcutsTitle=true
editURL = "https://github.com/bettercap/website/edit/master/content/"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/bettercap/bettercap"
weight = 1

[[menu.shortcuts]] 
name = "<i class='fas fa-bullhorn'></i> Blog"
url = "https://www.evilsocket.net/tags/bettercap/"
weight = 2

[[menu.shortcuts]] 
name = '<br/><img alt="Software License" src="https://img.shields.io/badge/license-GPL3-brightgreen.svg?style=flat-square">'
url = "https://github.com/bettercap/bettercap/blob/master/LICENSE.md"
weight = 4

[[menu.shortcuts]] 
name = '<img alt="Travis" src="https://img.shields.io/travis/bettercap/bettercap/master.svg?style=flat-square">'
url = "https://travis-ci.org/bettercap/bettercap"
weight = 5

[[menu.shortcuts]] 
name = '<img alt="Go Report Card" src="https://goreportcard.com/badge/github.com/bettercap/bettercap?style=flat-square&fuckgithubcache=1">'
url = "https://goreportcard.com/report/github.com/bettercap/bettercap"
weight = 6

[[menu.shortcuts]] 
name = '<img alt="Go Doc" src="https://img.shields.io/badge/godoc-reference-blue.svg?style=flat-square">'
url = "http://godoc.org/github.com/bettercap/bettercap"
weight = 7

[[menu.shortcuts]] 
name = "<br><i class='fas fa-bookmark'></i> Legacy v1.x Doc"
url = "/legacy/"
weight = 8
